pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-north-1'
    }

    stages {
        stage('Terraform Init') {
            steps {
                script {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Run Cost Analysis') {
            steps {
                script {
                    sh 'python3 scripts/my_spark_job.py'
                }
            }
        }

        stage('Validate Results') {
            steps {
                script {
                    sh 'python3 scripts/validate_data.py'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
