- name: Setup Hadoop Ecosystem on Kubernetes
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Kubernetes CLI
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Install Ansible Kubernetes module
      pip:
        name: openshift

    - name: Configure kubeconfig
      shell: aws eks update-kubeconfig --region us-west-2 --name hadoop-eks-cluster
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Deploy Hadoop using Helm
      shell: helm repo add stable https://charts.helm.sh/stable && helm repo update && helm install hadoop-cluster stable/hadoop

    - name: Setup Kerberos
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - krb5-admin-server
        - krb5-kdc
      when: kerberos_enabled | default(true)

    - name: Create new Kerberos realm
      shell: sudo krb5_newrealm
      when: kerberos_enabled | default(true)

    - name: Install Apache Ranger
      apt:
        name: ranger
        state: present
      when: ranger_enabled | default(true)
